# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 07:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='send_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u53d1\u9001\u7684\u65f6\u95f4'),
        ),
    ]
