# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171111_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='receiver_id',
            field=models.IntegerField(default=0, verbose_name='\u662f\u5426\u9ed8\u8ba4'),
        ),
    ]
