# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 17:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateField(auto_now_add=True, null=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goodsinfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.GoodsInfo')),
            ],
            options={
                'verbose_name': '\u8bbf\u95ee\u4fe1\u606f',
                'verbose_name_plural': '\u8bbf\u95ee\u4fe1\u606f',
            },
        ),
    ]
