# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20171117_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecord',
            name='access_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
