# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0004_auto_20171117_2204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecord',
            unique_together=set([('account', 'goodsinfo')]),
        ),
    ]
